{% set name = "keyrings.codeartifact" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/keyrings_codeartifact-{{ version }}.tar.gz
  sha256: ac7b0082840216ee5445c786b5b6c599a455cb3a0dc02dd40fd4d50d0bcaac2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - keyring
    - boto3

test:
  imports:
    - keyrings
    - keyrings.codeartifact
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jmkeyes/keyrings.codeartifact
  summary: Automatically retrieve credentials for AWS CodeArtifact.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jmkeyes
